-- Fix employee passwords with correctly generated BCrypt hash for 'password123'
-- Hash generated by Spring BCryptPasswordEncoder (verified)
UPDATE employees 
SET password = '$2a$10$YUTSWZqAVuPEgUlE3GXwTOjnb43yoO5XlxDIfehkJO8lYs204HlHS'
WHERE email IN (
    'jane@company.com',
    'meena@company.com', 
    'vikram@company.com',
    'ananya@company.com',
    'rahul@company.com',
    'priya@company.com'
);

SELECT id, name, email, role, LEFT(password, 10) as hash_prefix FROM employees;
