/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  // v2.0: CSS-variable-driven semantic colors — all theme-aware
  theme: {
    extend: {
      "colors": {
        // ── Static palette tokens ───────────────────────────────────────────
        "surface-container-low": "#eff4ff",
        "background": "#f8f9ff",
        "secondary-fixed": "#85f8c4",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#544fc0",
        "surface-container": "#e5eeff",
        "tertiary": "#482300",
        "inverse-primary": "#c3c0ff",
        "tertiary-fixed-dim": "#ffb77d",
        "secondary-fixed-dim": "#68dba9",
        "on-primary-container": "#a9a7ff",
        "on-background": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-secondary-container": "#00714e",
        "secondary-container": "#82f5c1",
        "primary-fixed-dim": "#c3c0ff",
        "primary-fixed": "#e2dfff",
        "on-tertiary-fixed": "#2f1500",
        "on-primary-fixed": "#0f0069",
        "on-primary-fixed-variant": "#3b35a7",
        "tertiary-fixed": "#ffdcc3",
        "inverse-on-surface": "#eaf1ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "inverse-surface": "#213145",
        "on-secondary-fixed-variant": "#005137",
        "on-tertiary-container": "#ff9631",
        "tertiary-container": "#683600",
        // ── CSS-variable-driven semantic tokens (theme-aware) ───────────────
        // These keys map to CSS custom properties, making dark mode seamless.
        "surface":              "rgb(var(--surface) / <alpha-value>)",
        "surface-variant":      "rgb(var(--surface-variant) / <alpha-value>)",
        "on-surface":           "rgb(var(--on-surface) / <alpha-value>)",
        "on-surface-variant":   "rgb(var(--on-surface-variant) / <alpha-value>)",
        "primary":              "rgb(var(--primary) / <alpha-value>)",
        "on-primary":           "rgb(var(--on-primary) / <alpha-value>)",
        "primary-container":    "rgb(var(--primary-container) / <alpha-value>)",
        "on-primary-container": "rgb(var(--on-primary-container-text) / <alpha-value>)",
        "secondary":            "rgb(var(--secondary) / <alpha-value>)",
        "on-secondary":         "rgb(var(--on-secondary) / <alpha-value>)",
        "error":                "rgb(var(--error) / <alpha-value>)",
        "on-error":             "rgb(var(--on-error) / <alpha-value>)",
        "error-container":      "rgb(var(--error-container) / <alpha-value>)",
        "on-error-container":   "rgb(var(--on-error-container) / <alpha-value>)",
        "outline":              "rgb(var(--outline) / <alpha-value>)",
        "outline-variant":      "rgb(var(--outline-variant) / <alpha-value>)",
        // ── Semantic status colors — NOW PROPERLY MAPPED ────────────────────
        "success":              "rgb(var(--success) / <alpha-value>)",
        "success-container":    "rgb(var(--success-container) / <alpha-value>)",
        "on-success":           "rgb(var(--on-success) / <alpha-value>)",
        "warning":              "rgb(var(--warning) / <alpha-value>)",
        "warning-container":    "rgb(var(--warning-container) / <alpha-value>)",
        "on-warning":           "rgb(var(--on-warning) / <alpha-value>)",
        "info":                 "rgb(var(--info) / <alpha-value>)",
        "info-container":       "rgb(var(--info-container) / <alpha-value>)",
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sm": "8px",
        "lg": "24px",
        "xs": "4px",
        "xl": "32px",
        "gutter": "16px",
        "md": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "unit": "4px"
      },
      "fontFamily": {
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "display": ["Inter"],
        "body-lg": ["Inter"],
        "mono": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "mono": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
