/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-low": "#eff4ff",
        "background": "#f8f9ff",
        "secondary-fixed": "#85f8c4",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#544fc0",
        "error": "#ba1a1a",
        "surface-container": "#e5eeff",
        "tertiary": "#482300",
        "inverse-primary": "#c3c0ff",
        "secondary": "#006c4a",
        "tertiary-fixed-dim": "#ffb77d",
        "secondary-fixed-dim": "#68dba9",
        "on-surface": "#0b1c30",
        "on-primary-container": "#a9a7ff",
        "on-background": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#464553",
        "surface-container-highest": "#d3e4fe",
        "on-error": "#ffffff",
        "surface": "#f8f9ff",
        "on-secondary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-secondary-container": "#00714e",
        "secondary-container": "#82f5c1",
        "primary-fixed-dim": "#c3c0ff",
        "primary-fixed": "#e2dfff",
        "on-tertiary-fixed": "#2f1500",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#0f0069",
        "on-error-container": "#93000a",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#3b35a7",
        "tertiary-fixed": "#ffdcc3",
        "primary": "#1f108e",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#777584",
        "outline-variant": "#c8c4d5",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "inverse-surface": "#213145",
        "on-secondary-fixed-variant": "#005137",
        "primary-container": "#3730a3",
        "on-tertiary-container": "#ff9631",
        "tertiary-container": "#683600"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sm": "8px",
        "lg": "24px",
        "xs": "4px",
        "xl": "32px",
        "gutter": "16px",
        "md": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "unit": "4px"
      },
      "fontFamily": {
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "display": ["Inter"],
        "body-lg": ["Inter"],
        "mono": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "mono": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
